### PR TITLE
add ci.Dockerfile and build script

### PR DESCRIPTION
**Pull request by andrewmarklloyd**
rest api for continuous integration purposes

### CODE REVIEW

**Comment by jasonify** [comment]
Sorry I didn't get to this sooner, can we resolve the conflicts?

**Comment by joshmorel** [comment]
As mentioned in Slack devops channel - I'm not sure if this was intended or the PR was supposed to be from `ci-build` to `develop`. Nonetheless I needed to update this so the rest image was again using the right env variable for the mongo image - `MONGO_HOST=mongodb://mongo/sedaily`. I changed to using an explicit `.env` file as otherwise someone may not know that `.env.docker_example` is used for this purposes and may introduce a breaking change, however this does increase the number of places where `.env` files must be updated if lets say a service is added.

An alternate option may be to add more defaults in the `config/config.js` file and keep the `.env` examples minimal while removing it for CI. For example, we only care about `MAILCHIMP_KEY` in production, staging and by those doing specific development for it. It isn't needed by most developers and in CI - so add a "fake" default in `config.js` and remove it from the example env files. For CI then... we could just use the docker file to define environment variables that important for CI.

I don't mind working on PR for this if it's agreed this is a better approach. I'm also open to other suggestions.

**Comment by abdulbasitkay** [comment]
Is this a wip or can it be merged in?

**Comment by joshmorel** [comment]
There would be no harm in merging it as it does't affect anything else, however, we're really blocked on operationalizing this due to some of the larger issues with `sedaily-miner` integration described in #251 . I'd advise leaving it as WIP.

**Pull request closed without merging**
