### PR TITLE
Add Travis CI automation to create dockerized backend

### PR DESCRIPTION
**Pull request by andrewmarklloyd**

### CODE REVIEW

**Comment by joshmorel** [comment]
Andrew, Took a review and was hoping to fully try it out with back-end/front-end development but there seems to be some issue with the mongo archive used in the image. All collections are there but most are empty. Only `tags` and `forumthreads` have data in them. 

Also, simple thing to add, but we should be using the sedaily-mongo image in the docker-compose file.

Just switch   `image: "mongo:3.4.2"` with `image: softwaredaily/sedaily-mongo:develop`

**Comment by andrewmarklloyd** [comment]
Thanks I’ll make the image change. As far as the collections, I think it has to do with my instance of Mongo that I’m using to run mongodump. I was having problems with the miner. I’ll see if @jasonify can switch it to staging

**Comment by andrewmarklloyd** [comment]
@joshmorel I fixed my version of the miner and MongoDB so it should be good. For now the CI can run a `mongodump` against my Mongo instance.

**Comment by joshmorel** [comment]
@andrewmarklloyd  Back-end looks works and front-end runs with no errors (amazing!). 

I can start looking at that Cypress e2e testing again tomorrow. For this work, what are the next steps?

**Comment by andrewmarklloyd** [comment]
@joshmorel I think you’ll just have to change the Docker image name.

https://github.com/joshmorel/sedaily-front-end/blob/2fb7dc1f91182b6e2b49fd43e6536e29a36a27ac/devops/docker-compose.yml

I’m not sure about the rest of the work you started.

**Comment by joshmorel** [comment]
Oops that came across incorrectly. I'm good on updating the compose file.

I meant, what are the next steps to get these docker images into sustainable use (e.g. as new commits are made to the back-end)?

**Comment by andrewmarklloyd** [comment]
Oh in that case, they’re fully automated and functional at this point. The only change would be to run mongodump against staging instead of against my Mongo instance. That just requires @jasonify to change the Travis CI environment variables to for the Mongodb config. But the e2e tests will be able to run now.

**Pull request merged**
