### PR TITLE
Add info about 'Ready For Review' label

### PR DESCRIPTION
**Pull request by andrewmarklloyd**

### CODE REVIEW

**Comment by TheHollidayInn** [comment]
I'm not sure the normal contributor would be able to add their own labels. Aren't only team members allowed?

**Comment by andrewmarklloyd** [comment]
Yeah that's a good point.

**Comment by TheHollidayInn** [comment]
If you want to add a section for the review process then we can merge that! This way contributors will know what to expect from us

**Comment by andrewmarklloyd** [comment]
What all should it include? 
- you'll set the label to 'ready for review'
- do you want to include using the [WIP] tag for work in progress?

**Pull request closed without merging**
