### PR TITLE
disable the rule not allowing arrow functions with a single line in b…

### LINKED ISSUE #237: Disable eslint error on arrow function with one line
A good example is found in forumThread.model.js

```
  const threadsFoundProcessed = threadsFound.map((thread) => {
          console.log('-');
          return Object.assign({}, thread.toObject());
        });

```

### PR DESCRIPTION
**Pull request by rugglcon**
…races and remove eslint disable comments that are now unncessary

Fixes #237

### CODE REVIEW

**Comment by rugglcon** [comment]
The build failed because of something wrong with the build environment, I didn't change anything related to why the docker build would fail. The error message is
```
The command "./devops/build-api.sh" exited with 1.
12.52s$ cd devops; ./build-mongodb.sh
2018-08-19T02:54:08.894+0000	error parsing command line options: expected argument for flag `-h, --host', but got option `--port'
2018-08-19T02:54:08.894+0000	try 'mongodump --help' for more information
2018-08-19T02:54:08.908+0000	error parsing command line options: expected argument for flag `-h, --host', but got option `--username'
2018-08-19T02:54:08.908+0000	try 'mongodump --help' for more information
mv: cannot stat ‘backup//*’: No such file or directory
```

**Comment by andrewmarklloyd** [comment]
@rugglcon the issue is that the build relies on connecting to the staging MongoDB, which needs secure Travis CI environment variables. Those environment variables cannot be exposed in a [pull request](https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions). I need to update the .travis.yml to only build on successful merges into develop and not pull requests.

**Comment by andrewmarklloyd** [comment]
@rugglcon try to merge my latest changes from develop into your branch and push back up. I believe the Docker job will not run on PR's now.

**Comment by rugglcon** [comment]
Thanks, I'll pull that down later tonight and merge it into my branch

**Comment by rugglcon** [comment]
looks like that fixed it, thank you @andrewmarklloyd

**Comment by rugglcon** [comment]
Is this good to go in? or was this fixed at another time? The issue this fixes is still open as well.

**Comment by andrewmarklloyd** [comment]
Hey @rugglcon sorry for the 11 month delay. It’s all merged now thanks!

**Pull request merged**
