### PR TITLE
refactor config

### PR DESCRIPTION
**Pull request by joshmorel**
not sure what happened to the git history in #240 but this is clean...

also update Dockerfile to same version of travis.yml

### CODE REVIEW

**Comment by jasonify** [comment]
Thanks for doing this, though I think it will be extra slow to get this particular PR merged in since it deals with sensitive parts of the code, mainly the Stripe keys (which are annoying to test in production, require a real CC).

**Comment by jasonify** [comment]
Took a quick look, it looks good, next steps are:

[ ] add missing keys to travis
[ ] test locally
[ ] test in staging
[ ] test in production

**Comment by joshmorel** [comment]
I understand and am not in hurry - but, why wouldn't we test the stripe key works in staging using a [test card like '4242 4242 4242 4242'](https://stripe.com/docs/testing)?

**Comment by jasonify** [comment]
That's right, that's the way we test staging and local host

**Comment by jasonify** [comment]
Yeah, sadly we have had some problems where staging differed  from prod (though it was a mistyped Mailchimp API key, hard to spot, was causing people to not be able to register)... so it's made me a little paranoid. 

In theory this should work no problem if it works on staging.

If it's blocking the cloud9 stuff let me know, and I can move it up my queue. Though I also want other people to review this PR if possible.

**Comment by joshmorel** [comment]
I can understand the concerns - hopefully at some point we can be confident that if staging is working we don't need to test external integrations again in productions :slightly_smiling_face: 

For Cloud9, some exploratory work will be required so I can't imagine that not merging in a timely manner would block this work. @abdulbasitkay is taking the lead so can let us know when action is required.

**Pull request closed without merging**
