### PR TITLE
Vote controller logic

### LINKED ISSUE #6: Vote controller has old/unused code
The vote logic is currently in the post controller. We need to organize it into the vote controller and remove the old unused code.

### PR DESCRIPTION
**Pull request by andrewmarklloyd**
Resolves #6. Moved upvote and downvote logic to the vote controller. Removed unused code in vote controller. Improve vote unit tests

### CODE REVIEW

**Comment by TheHollidayInn** [comment]
This replaces my PR #10 correct?

**Comment by andrewmarklloyd** [comment]
Yeah that's correct, I figured since I was already making changes there it made sense to do.

**Comment by TheHollidayInn** [comment]
Perfect! Just making sure.

**Comment by TheHollidayInn** [comment]
Looks great! Thanks :D

**Pull request merged**
